version: "3"

services:
  transmission:
    container_name: transmission
    image: jaymoulin/transmission
    ports:
      - "9091:80"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    environment:
      PORT: 80
    volumes:
      - ${WATCH_DIR}:/to_download
      - ${DOWNLOAD_DIR}:/output
      - config:/config
    restart: unless-stopped

volumes:
  config:
