version: "3.4"

services:
  transmission:
    container_name: transmission
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      PORT: 9091
    volumes:
      - ${WATCH_DIR}:/watch
      - ${DOWNLOAD_DIR}:/media
      - ${RESUME_DIR}:/config/resume
      - ${TORRENTS_DIR}:/config/torrents
      - config:/config
    restart: unless-stopped

volumes:
  config:
