version: "3.4"

services:
  transmission:
    container_name: transmission
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      PORT: 9091
      DOWNLOAD_PATH: ${DOWNLOAD_PATH}
    volumes:
      - ${MEDIA_DIR}:/media
      - ${WATCH_DIR}:/watch
      - ${RESUME_DIR}:/config/resume
      - ${TORRENTS_DIR}:/config/torrents
      - config:/config
    restart: unless-stopped

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:1
    environment:
      DOMAINS: ${HTTPS_PORTAL_USER}:${HTTPS_PORTAL_PASSWORD}@${DOMAIN} -> http://127.0.0.1:9091
      STAGE: ${HTTPS_PORTAL_STAGE}
    volumes:
      - https-portal_certs:/var/lib/https-portal
    network_mode: host
    depends_on:
      - transmission
    restart: unless-stopped

volumes:
  config:
  https-portal_certs:
