version: "3"

services:
  transmission:
    container_name: transmission
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:80"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    environment:
      PORT: 80
    volumes:
      - ${WATCH_DIR}:/watch
      - ${DOWNLOAD_DIR}:/media
      - ${RESUME_DIR}:/config/resume
      - ${TORRENTS_DIR}:/config/torrents
      - config:/config
    restart: unless-stopped

volumes:
  config:
