services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:${VERSION}
    network_mode: host
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${WATCH_DIR}:/watch
    restart: unless-stopped

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:1
    stop_signal: SIGINT
    environment:
      DOMAINS: >
        ${HTTPS_PORTAL_USER}:${HTTPS_PORTAL_PASSWORD}@${DOMAIN} -> http://127.0.0.1:9091,
        ${EXTRA_SITES}
      CLIENT_MAX_BODY_SIZE: 1024M
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
      STAGE: ${HTTPS_PORTAL_STAGE}
    volumes:
      - https-portal_certs:/var/lib/https-portal
    network_mode: host
    depends_on:
      - transmission
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "3"

volumes:
  config:
  https-portal_certs:
