#!/bin/sh

set -x

trap 'kill -TERM $PID' TERM INT

if [ "$#" -eq 0 ]; then
  transmission-daemon \
    --watch-dir /watch \
    --download-dir /media \
    --incomplete-dir /media/.incoming \
    --foreground \
    --no-auth \
    --allowed *.*.*.* \
    --port "$PORT" \
    --portmap \
    --config-dir /config &
else
  transmission-daemon $@ &
fi

PID=$!
wait $PID
wait $PID
while [ -f /config/lock ]; do
  sleep 2
done

EXIT_STATUS=$?
